import { parseTemplateVariables } from "./template-parser"
import { resolveVariables } from "./variable-resolver"
import { evaluateConditions } from "./conditional-evaluator"
import { generateDocx, validateTemplate } from "./docx-generator"
import { generatePdfFromData, generateSimplePdf } from "./pdf-generator"
import {
  spellOutCurrency,
  formatLegalNumber,
  formatLegalDate,
  formatPercentage,
  formatCurrency,
} from "./number-formatter"
import Handlebars from "handlebars"

interface FieldDefinition {
  variable: string
  type: string
  config?: Record<string, unknown>
  options?: Array<{ label: string; value: string }>
}

interface GenerateResult {
  buffer: Buffer
  contentType: string
  fileName: string
}

// Register Handlebars helpers
Handlebars.registerHelper("ifEquals", function (
  this: unknown,
  arg1: unknown,
  arg2: unknown,
  options: Handlebars.HelperOptions
) {
  return arg1 === arg2 ? options.fn(this) : options.inverse(this)
})

Handlebars.registerHelper("formatCurrency", function (amount: number) {
  return formatCurrency(amount)
})

Handlebars.registerHelper("formatDate", function (date: string) {
  return formatLegalDate(date)
})

Handlebars.registerHelper("spellOut", function (amount: number) {
  return spellOutCurrency(amount)
})

export async function generateDocument(
  templateBuffer: Buffer | null,
  answers: Record<string, unknown>,
  fields: FieldDefinition[],
  format: "docx" | "pdf" | "html",
  templateName: string = "Document"
): Promise<GenerateResult> {
  // Resolve variables from raw answers
  const resolvedData = resolveVariables(answers, fields)

  switch (format) {
    case "docx": {
      if (!templateBuffer) {
        throw new Error("Template file is required for .docx generation")
      }
      const buffer = generateDocx(templateBuffer, resolvedData)
      return {
        buffer,
        contentType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        fileName: `${sanitizeFileName(templateName)}.docx`,
      }
    }

    case "pdf": {
      const buffer = await generatePdfFromData(resolvedData, templateName)
      return {
        buffer,
        contentType: "application/pdf",
        fileName: `${sanitizeFileName(templateName)}.pdf`,
      }
    }

    case "html": {
      const html = generateHtml(resolvedData, templateName)
      const buffer = Buffer.from(html, "utf-8")
      return {
        buffer,
        contentType: "text/html",
        fileName: `${sanitizeFileName(templateName)}.html`,
      }
    }

    default:
      throw new Error(`Unsupported format: ${format}`)
  }
}

function generateHtml(data: Record<string, unknown>, title: string): string {
  const template = Handlebars.compile(`
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title}}</title>
  <style>
    body { font-family: 'Times New Roman', Times, serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a; line-height: 1.6; }
    h1 { font-size: 24px; border-bottom: 2px solid #333; padding-bottom: 8px; margin-bottom: 24px; }
    .field { margin-bottom: 16px; }
    .field-label { font-weight: bold; color: #555; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 4px; }
    .field-value { font-size: 14px; }
    .generated-date { color: #999; font-size: 12px; margin-bottom: 32px; }
    .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 11px; color: #999; }
  </style>
</head>
<body>
  <h1>{{title}}</h1>
  <div class="generated-date">Generated: {{generatedDate}}</div>
  {{#each fields}}
  <div class="field">
    <div class="field-label">{{this.label}}</div>
    <div class="field-value">{{this.value}}</div>
  </div>
  {{/each}}
  <div class="footer">Generated by DocGen</div>
</body>
</html>
  `)

  const fields = Object.entries(data)
    .filter(([key, value]) => {
      if (key.endsWith("_raw") || key.endsWith("_legal") || key.endsWith("_short") ||
          key.endsWith("_spelled") || key.endsWith("_formatted") || key.endsWith("_label") ||
          key.endsWith("_labels") || key.endsWith("_joined") || key.endsWith("_full") ||
          key.endsWith("_text")) {
        return false
      }
      return value !== null && value !== undefined && value !== ""
    })
    .map(([key, value]) => ({
      label: key.replace(/_/g, " ").replace(/\b\w/g, (l) => l.toUpperCase()),
      value: formatHtmlValue(value),
    }))

  return template({
    title,
    generatedDate: new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    }),
    fields,
  })
}

function formatHtmlValue(value: unknown): string {
  if (value === null || value === undefined) return ""
  if (typeof value === "boolean") return value ? "Yes" : "No"
  if (Array.isArray(value)) return value.map(String).join(", ")
  if (typeof value === "object") return JSON.stringify(value, null, 2)
  return String(value)
}

function sanitizeFileName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9\s-_]/g, "")
    .replace(/\s+/g, "-")
    .toLowerCase()
    .slice(0, 100)
}

export {
  parseTemplateVariables,
  resolveVariables,
  evaluateConditions,
  generateDocx,
  validateTemplate,
  generatePdfFromData,
  generateSimplePdf,
  spellOutCurrency,
  formatLegalNumber,
  formatLegalDate,
  formatPercentage,
  formatCurrency,
}
