import { PDFDocument, StandardFonts, rgb } from "pdf-lib"

interface ContentItem {
  label: string
  value: string
}

export async function generatePdfFromData(
  data: Record<string, unknown>,
  templateName: string
): Promise<Buffer> {
  const items: ContentItem[] = Object.entries(data)
    .filter(([, value]) => value !== null && value !== undefined && value !== "")
    .map(([key, value]) => ({
      label: formatLabel(key),
      value: formatValue(value),
    }))

  return generateSimplePdf(templateName, items)
}

export async function generateSimplePdf(
  title: string,
  content: ContentItem[]
): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create()
  const timesRoman = await pdfDoc.embedFont(StandardFonts.TimesRoman)
  const timesRomanBold = await pdfDoc.embedFont(StandardFonts.TimesRomanBold)
  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica)

  const pageWidth = 612 // Letter size
  const pageHeight = 792
  const margin = 72 // 1 inch
  const lineHeight = 16
  const sectionGap = 8

  let page = pdfDoc.addPage([pageWidth, pageHeight])
  let yPosition = pageHeight - margin

  // Title
  page.drawText(title, {
    x: margin,
    y: yPosition,
    size: 20,
    font: timesRomanBold,
    color: rgb(0.1, 0.1, 0.1),
  })
  yPosition -= 12

  // Underline
  page.drawLine({
    start: { x: margin, y: yPosition },
    end: { x: pageWidth - margin, y: yPosition },
    thickness: 1,
    color: rgb(0.7, 0.7, 0.7),
  })
  yPosition -= 24

  // Date
  page.drawText(`Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, {
    x: margin,
    y: yPosition,
    size: 10,
    font: helvetica,
    color: rgb(0.5, 0.5, 0.5),
  })
  yPosition -= 30

  // Content
  for (const item of content) {
    // Check if we need a new page
    if (yPosition < margin + 40) {
      page = pdfDoc.addPage([pageWidth, pageHeight])
      yPosition = pageHeight - margin
    }

    // Label
    page.drawText(item.label, {
      x: margin,
      y: yPosition,
      size: 10,
      font: timesRomanBold,
      color: rgb(0.3, 0.3, 0.3),
    })
    yPosition -= lineHeight

    // Value - handle long text by wrapping
    const maxLineWidth = pageWidth - 2 * margin
    const valueLines = wrapText(item.value, timesRoman, 11, maxLineWidth)

    for (const line of valueLines) {
      if (yPosition < margin + 20) {
        page = pdfDoc.addPage([pageWidth, pageHeight])
        yPosition = pageHeight - margin
      }

      page.drawText(line, {
        x: margin,
        y: yPosition,
        size: 11,
        font: timesRoman,
        color: rgb(0.1, 0.1, 0.1),
      })
      yPosition -= lineHeight
    }

    yPosition -= sectionGap
  }

  // Footer on last page
  const lastPage = pdfDoc.getPages()[pdfDoc.getPageCount() - 1]
  lastPage.drawText("Generated by DocGen", {
    x: margin,
    y: 36,
    size: 8,
    font: helvetica,
    color: rgb(0.6, 0.6, 0.6),
  })

  const pdfBytes = await pdfDoc.save()
  return Buffer.from(pdfBytes)
}

function wrapText(
  text: string,
  _font: unknown,
  fontSize: number,
  maxWidth: number
): string[] {
  const textStr = String(text || "")
  const words = textStr.split(/\s+/)
  const lines: string[] = []
  let currentLine = ""

  for (const word of words) {
    const testLine = currentLine ? `${currentLine} ${word}` : word
    // Approximate width: ~6 pixels per character at 11pt
    const approxWidth = testLine.length * fontSize * 0.5

    if (approxWidth > maxWidth && currentLine) {
      lines.push(currentLine)
      currentLine = word
    } else {
      currentLine = testLine
    }
  }

  if (currentLine) {
    lines.push(currentLine)
  }

  return lines.length > 0 ? lines : [""]
}

function formatLabel(key: string): string {
  return key
    .replace(/_/g, " ")
    .replace(/([A-Z])/g, " $1")
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(" ")
    .trim()
}

function formatValue(value: unknown): string {
  if (value === null || value === undefined) return ""
  if (typeof value === "boolean") return value ? "Yes" : "No"
  if (typeof value === "object") {
    if (Array.isArray(value)) return value.map(String).join(", ")
    return JSON.stringify(value)
  }
  return String(value)
}
